#!/usr/bin/env bash
#A bash script that configures and install nginx on our server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
