#!/usr/bin/env bash
# Installs 'nginx' on your server with the following requirement
#	- Listens to port 80
#	- Returns a page containing the string 'Hello World' when querying
#	  it root directory

# Update the package list from all configured sources
apt-get update;
# Install the 'nginx' from apt store
apt-get install nginx -y;

mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/custom_404.html

echo "server {
	listen	80 default_server;
	listen	[::]:80 default_server;

	root	/etc/nginx/html;
	index	index.html;

	error_page 404 /custom_404.html;
	location /custom_404.html {
	    root /etc/nginx/html;
	    internal;
    	}
}" > /etc/nginx/sites-available/default

service nginx restart
